version: '3.8'

services:

  db:
    image: postgres:15-alpine
    container_name: cityguide-db
    environment:
      POSTGRES_DB: city_guide_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Snik2005!
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d city_guide_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: cityguide-app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/city_guide_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Snik2005!

volumes:
  pgdata: 